### ISSUE TITLE
Issue with running experiment

### ISSUE THREAD

**Issue by micwinter** [drewlinsley/contextual_circuit_bp#9]
running a an experiment using `sudo CUDA_VISIBLE_DEVICES=0 python main.py --experiment=MULTIALLEN_VISpm_l234_Cux2yZCJqzZYqrESlJRJ`
results in the following error
`I0032 2018-01-10 17:50:30.374308 main.py:124 Log written to /media/data_cifs/contextual_circuit/logs/MULTIALLEN_VISpm_l234_Cux2yZCJqzZYqrESlJRJ_2018_01_10_17_50_30`
`Traceback (most recent call last):`
`  File "main.py", line 456, in <module>`
`  main(**vars(args))`
`  File "main.py", line 134, in main`
`    config=config)  # Update config w/ DB params`
`  File "main.py", line 44, in process_DB_exps`
`    evaluation=config.load_and_evaluate_ckpt)`
`AttributeError: Config instance has no attribute 'load_and_evaluate_ckpt'`

**Comment by drewlinsley** [comment]
Fixed these bugs.
